# Generated by Django 3.2.12 on 2022-03-18 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_acteur', models.CharField(max_length=50)),
                ('pays_acteur', models.CharField(max_length=50)),
                ('image_acteur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_genre', models.CharField(max_length=30)),
                ('definition_genre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateform', models.CharField(max_length=50)),
                ('prix_plateform', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('date_question', models.DateTimeField(verbose_name='date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_realisateur', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_serie', models.CharField(max_length=20)),
                ('description_serie', models.CharField(max_length=20)),
                ('image_serie', models.CharField(max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('realisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.realisateur')),
            ],
        ),
    ]
