# Generated by Django 3.2.12 on 2022-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='definition_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
