# Generated by Django 3.2.12 on 2022-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_genre_definition_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='realisateur',
            new_name='realisateur_serie',
        ),
        migrations.RenameField(
            model_name='serie',
            old_name='votes',
            new_name='votes_serie',
        ),
    ]
