# Generated by Django 3.2.12 on 2022-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20220318_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='experience_acteur',
            field=models.DateField(blank=b'I01\n', null=True),
        ),
    ]
