# Generated by Django 3.2.12 on 2022-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_acteur_experience_acteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='question',
            field=models.ManyToManyField(to='vote.Question'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description_serie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serie',
            name='image_serie',
            field=models.CharField(max_length=255),
        ),
    ]
