# Generated by Django 3.2.12 on 2022-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20220321_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='question',
            field=models.ManyToManyField(blank=True, to='vote.Question'),
        ),
    ]
