# Generated by Django 4.0.3 on 2022-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_auto_20220321_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='description_serie',
            field=models.TextField(),
        ),
    ]
